import { RiskStatus, NodeTier, type RiskNodeData, type ContagionPath } from '../types';

export const NODES: RiskNodeData[] = [
  // L0: 成员公司
  {
    id: 'L1-001',
    label: '平安银行',
    level: 0,
    status: RiskStatus.ALERT,
    tier: NodeTier.TIER1,
    children: ['L2-001', 'L2-002'],
    ldcAmount: 5600000,
    rcsaDefects: 5,
    auditIssues: 3,
    penaltyCount: 1,
    healthScore: 72,
    duration: '2天',
  },
  {
    id: 'L1-002',
    label: '平安产险',
    level: 0,
    status: RiskStatus.NORMAL,
    tier: NodeTier.TIER1,
    ldcAmount: 120000,
    rcsaDefects: 2,
    auditIssues: 1,
    penaltyCount: 0,
    healthScore: 94,
    duration: '30天+',
  },
  {
    id: 'L1-003',
    label: '平安人寿',
    level: 0,
    status: RiskStatus.WARNING,
    tier: NodeTier.TIER1,
    ldcAmount: 450000,
    rcsaDefects: 8,
    auditIssues: 4,
    penaltyCount: 1,
    healthScore: 82,
    duration: '5天',
  },
  // L1: 一级流程框架
  {
    id: 'L2-001',
    label: '运营管理框架',
    level: 1,
    parent: 'L1-001',
    status: RiskStatus.ALERT,
    tier: NodeTier.TIER1,
    children: ['L3-001'],
    ldcAmount: 1200000,
    rcsaDefects: 3,
    auditIssues: 2,
    penaltyCount: 1,
    healthScore: 65,
    duration: '2天',
  },
  {
    id: 'L2-002',
    label: '财务管理框架',
    level: 1,
    parent: 'L1-001',
    status: RiskStatus.WARNING,
    tier: NodeTier.TIER2,
    children: ['L3-002'],
    ldcAmount: 0,
    rcsaDefects: 1,
    auditIssues: 1,
    penaltyCount: 0,
    healthScore: 78,
    duration: '4天',
  },
  // L2: 二级流程框架
  {
    id: 'L3-001',
    label: '客户服务与运营',
    level: 2,
    parent: 'L2-001',
    status: RiskStatus.ALERT,
    tier: NodeTier.TIER1,
    children: ['L4-001'],
    ldcAmount: 1200000,
    rcsaDefects: 3,
    auditIssues: 2,
    penaltyCount: 1,
    healthScore: 60,
    duration: '2天',
  },
  {
    id: 'L3-002',
    label: '财务管理',
    level: 2,
    parent: 'L2-002',
    status: RiskStatus.WARNING,
    tier: NodeTier.TIER2,
    children: ['L4-002'],
    ldcAmount: 0,
    rcsaDefects: 1,
    auditIssues: 1,
    penaltyCount: 0,
    healthScore: 75,
    duration: '4天',
  },
  // L3: 主业务流程
  {
    id: 'L4-001',
    label: '理赔运营管理',
    level: 3,
    parent: 'L3-001',
    status: RiskStatus.ALERT,
    tier: NodeTier.TIER1,
    children: ['L5-001', 'L5-002', 'L5-004', 'L5-005'],
    ldcAmount: 1200000,
    rcsaDefects: 3,
    auditIssues: 2,
    penaltyCount: 1,
    healthScore: 55,
    duration: '2天',
  },
  {
    id: 'L4-002',
    label: '财务核算管理',
    level: 3,
    parent: 'L3-002',
    status: RiskStatus.WARNING,
    tier: NodeTier.TIER2,
    children: ['L5-003', 'L5-006'],
    ldcAmount: 0,
    rcsaDefects: 1,
    auditIssues: 1,
    penaltyCount: 0,
    healthScore: 73,
    duration: '4天',
  },
  // L4: 子业务流程
  {
    id: 'L5-001',
    label: '理赔资金结算',
    level: 4,
    parent: 'L4-001',
    status: RiskStatus.ALERT,
    tier: NodeTier.TIER1,
    ldcAmount: 1200000,
    rcsaDefects: 3,
    auditIssues: 2,
    penaltyCount: 1,
    healthScore: 45,
    duration: '2天',
    description: '系统重复支付导致资金外溢，涉及大额理赔结算异常。',
    aiExplanation: '该节点为本次风险爆发的核心源头。由于前端理赔系统校验逻辑失效，导致同一批次理赔指令触发了双次银行转账，目前已触发高额 LDC 熔断机制。',
  },
  {
    id: 'L5-002',
    label: '理赔档案管理',
    level: 4,
    parent: 'L4-001',
    status: RiskStatus.NORMAL,
    tier: NodeTier.TIER3,
    ldcAmount: 0,
    rcsaDefects: 0,
    auditIssues: 0,
    penaltyCount: 0,
    healthScore: 98,
    duration: '60天+',
  },
  {
    id: 'L5-003',
    label: '财务对账流程',
    level: 4,
    parent: 'L4-002',
    status: RiskStatus.WARNING,
    tier: NodeTier.TIER2,
    ldcAmount: 0,
    rcsaDefects: 1,
    auditIssues: 1,
    penaltyCount: 0,
    healthScore: 72,
    duration: '4天',
    description: '对账不平，受理赔资金结算异常影响，导致财务报表偏离。',
    aiExplanation: '根据 LLM 物理拓扑推演，下游财务对账系统直接依赖理赔结算结果。由于上游数据污染，预期对账流程将产生严重阻塞，建议立即启动人工核查。',
  },
  {
    id: 'L5-004',
    label: '客户反欺诈管理',
    level: 4,
    parent: 'L4-001',
    status: RiskStatus.NORMAL,
    tier: NodeTier.TIER2,
    ldcAmount: 0,
    rcsaDefects: 0,
    auditIssues: 0,
    penaltyCount: 0,
    healthScore: 95,
    duration: '15天',
    isAIPredicted: true,
    contagionProbability: 85,
    aiExplanation: 'LLM 预测受影响路径：由于重复支付事件中可能包含黑产恶意套现行为，反欺诈系统可能面临识别规则绕过的潜在威胁。概率约为 85%。',
  },
  {
    id: 'L5-005',
    label: '客户回访满意度',
    level: 4,
    parent: 'L4-001',
    status: RiskStatus.NORMAL,
    tier: NodeTier.TIER3,
    ldcAmount: 0,
    rcsaDefects: 0,
    auditIssues: 0,
    penaltyCount: 0,
    healthScore: 99,
    duration: '100天+',
  },
  {
    id: 'L5-006',
    label: '预算执行监控',
    level: 4,
    parent: 'L4-002',
    status: RiskStatus.NORMAL,
    tier: NodeTier.TIER2,
    ldcAmount: 0,
    rcsaDefects: 0,
    auditIssues: 0,
    penaltyCount: 0,
    healthScore: 92,
    duration: '20天',
  },
];

export const PATHS: ContagionPath[] = [
  { source: 'L5-001', target: 'L5-003', isAI: false, reason: '物理血缘：财务系统结算依赖' },
  { source: 'L5-001', target: 'L5-004', isAI: true, probability: 85, reason: 'AI 预测：重复支付逻辑可能导致反欺诈规则库污染' },
];
